### PR TITLE
Remove DarkSky (RIP) weather provider

### PR DESCRIPTION
**Pull request by dgw**
Per Dark Sky's blog, the API will continue to work "until March 31st, 2023." The next release after that should include this patch to remove the no-longer-functional provider.

### CODE REVIEW

**Review by SnoopJ — APPROVED** [review]
Changes look fine to me, RIP

**Comment by dgw** [comment]
NB: #41 should fix the Actions failure.

**Comment by dgw** [comment]
Rebased after merge of #41; CI works now. Time to set a reminder for April 1?

**Comment by dgw** [comment]
Rebased again as merge of #43 caused conflicts. (I knew it would, tbf.)

**Pull request merged**
